# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`


In [3]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [5]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [6]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [7]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [8]:
a = np.array((1,2,0,0,4,0))
np.nonzero(a)

(array([0, 1, 4]),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [10]:
np.random.random([3,3,3])

array([[[0.38540542, 0.60399322, 0.49586938],
        [0.02583071, 0.12911631, 0.98052356],
        [0.0188656 , 0.76731271, 0.15868493]],

       [[0.49847835, 0.94070674, 0.83985367],
        [0.48218771, 0.83025136, 0.10771496],
        [0.63418329, 0.01999848, 0.01484717]],

       [[0.48290096, 0.53168212, 0.5733382 ],
        [0.99682496, 0.50605407, 0.86211996],
        [0.56594848, 0.20454107, 0.44028515]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [11]:
a = np.random.random(100)
print(a)

print(min(a))
print(max(a))

[0.13891275 0.91343154 0.46605779 0.47596029 0.3698618  0.87591808
 0.15693483 0.90260172 0.71055601 0.62334306 0.91899111 0.88947829
 0.27600863 0.20017842 0.26594185 0.16315488 0.85205513 0.58936608
 0.84050857 0.4394944  0.12936409 0.347871   0.69749981 0.93769667
 0.17908752 0.34389141 0.35396655 0.35536576 0.8039513  0.85694185
 0.01617895 0.99906417 0.41160499 0.09561189 0.82033731 0.53708365
 0.4394939  0.82439192 0.67575791 0.24451388 0.63070521 0.9087453
 0.28670687 0.08486831 0.3070325  0.59706971 0.86499587 0.57407452
 0.34036576 0.80709119 0.51966238 0.36582984 0.98695627 0.01811804
 0.55309139 0.19718528 0.71422342 0.32119578 0.10316927 0.2549298
 0.05093025 0.57778969 0.05140461 0.47391816 0.57892079 0.06870125
 0.89557117 0.19982919 0.83469784 0.05005071 0.49188679 0.37489888
 0.13907044 0.16348088 0.52283214 0.55022545 0.24183451 0.78649885
 0.57179732 0.29076994 0.12913265 0.00912292 0.10655927 0.98585449
 0.10285533 0.27314943 0.62300818 0.88061895 0.20009231 0.113011

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [12]:
a = np.random.random(30)
print(a)

np.mean(a)

[0.78223739 0.97196763 0.52452276 0.92788158 0.20588659 0.38325423
 0.55700458 0.39219971 0.65504545 0.88917566 0.38036631 0.35495289
 0.05180336 0.33024622 0.55052354 0.5542669  0.13936672 0.52775567
 0.19118598 0.44454769 0.98988365 0.04047078 0.54337113 0.14316134
 0.18113375 0.44215194 0.648105   0.48954482 0.93675631 0.2055246 ]


0.48114313899012673

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [13]:
a = np.diag([1,2,3,4], k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [14]:
a = np.random.randint(100, size=25).reshape(5,5)

print(a)

normalized = (a - np.mean(a))/(np.std(a))

print(normalized)

[[90 58 28 23  3]
 [77 42  5 18 92]
 [84 62 57 75 70]
 [26 91 16 91 84]
 [54 37 30 69 53]]
[[ 1.29458811  0.16270779 -0.89843    -1.0752863  -1.78271149]
 [ 0.83476173 -0.40323236 -1.71196897 -1.25214259  1.36533062]
 [ 1.08236055  0.30419283  0.12733653  0.76401921  0.58716291]
 [-0.96917252  1.32995937 -1.32288511  1.32995937  1.08236055]
 [ 0.02122276 -0.58008866 -0.82768748  0.55179165 -0.0141485 ]]



#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`


In [15]:
a = np.random.randint(100, size=25).reshape(5,5)
print(a)
b = np.random.randint(100, size=25).reshape(5,5)
print(b)

np.intersect1d(a,b)

[[72 85 71 25 10]
 [13 95 79 75 56]
 [83 23 33  2 31]
 [ 2 86 44 57 81]
 [ 4 67 39 80 53]]
[[46 87 98 22 77]
 [37 73 26 34 79]
 [ 5 77 73 94 78]
 [68 91 68 32 32]
 [42 47 44 58 90]]


array([44, 79])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [16]:
a = np.random.randint(100, size=10)
a

np.sort(a)

array([11, 30, 40, 45, 45, 51, 65, 76, 92, 96])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [17]:
a = np.random.randint(100, size=10)

a[a == max(a)] = 0

print(a)

[79 90 29 15 84 97  0 33 85 80]



#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [18]:
a = np.random.randint(100, size=25).reshape(5,5)
print(a)

x = np.mean(a, axis=1, keepdims=True)
print(x)

sub = (a - x)
print(sub)

[[47 45 17 11 86]
 [60 69 79 18 30]
 [19 47 88 87  4]
 [ 2 14 38  4 85]
 [66 66 63 25 65]]
[[41.2]
 [51.2]
 [49. ]
 [28.6]
 [57. ]]
[[  5.8   3.8 -24.2 -30.2  44.8]
 [  8.8  17.8  27.8 -33.2 -21.2]
 [-30.   -2.   39.   38.  -45. ]
 [-26.6 -14.6   9.4 -24.6  56.4]
 [  9.    9.    6.  -32.    8. ]]




#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [26]:
a = np.arange(10000)
np.random.shuffle(a)
n = 5
a

array([9912, 4772, 7373, ..., 5520, 2848, 1984])



#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [20]:
a = np.random.randint(100, size=15).reshape(5,3)
a

a[a > 4] = ((a > 4)**2)

TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions